### PR TITLE
Msee, nishamodify footer

### PR DESCRIPTION
**Pull request by edwin001-tech**
Ebu icheki uangalie kama ni responsive sasa

### CODE REVIEW

**Comment by edwin001-tech** [comment]
Alafu hio header width yako ni less sana
na font-size ya home pia ni minute sana
Alafu hizo paragraphs ziko home naona utumie color nyingine

**Comment by MbuguaGeorge** [comment]
alafu open hiyo link yangu kwa lappy alafu you minimize screen...hivo ndio nataka ikue

**Comment by MbuguaGeorge** [comment]
for example hiyo navigation, kwa fon inafaa kuwa different

**Comment by edwin001-tech** [comment]
Nisharesolve conflict na nikamerge commits

**Pull request merged**
